courses/urls.py
from django.urls import path
from courses import views


app_name = 'courses'

urlpatterns = [
    path('', views.index, name='main'),
    path('contacts', views.contacts, name='contacts'),
    path('courses/<int:pk>/', views.courses, name='courses'),
    path('courses/add', views.add_view_course, name='add_courses'),
    path('courses/edit/<int:pk>/', views.edit_view_course,
         name='edit_courses'),
    path('courses/delete/<int:pk>/', views.delete_course,
         name='delete_courses'),
    path('courses/add_lesson', views.add_view_lesson, name='add_lesson'),
    path('courses/edit_lesson/<int:pk>', views.edit_lesson,
         name='edit_lesson'),
    path('courses/delete_lesson/<int:pk>', views.delete_lesson,
         name='delete_lesson'),
    ]

hello/urls.py
from django.contrib import admin
from django.urls import path
from django.shortcuts import render
from django.urls import include
from students.views import students_list, students_all_list, students_id

# from instructors.views import hello,hello_http, views_about_course,views_student, views_student_detail, instructors_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('students/', include('students.urls', namespace='students')),
    path('coaches/', include('coaches.urls', namespace='coaches')),
]

students/urls.py
from django.urls import path
from students import views

app_name = 'students'

urlpatterns = [
    path('', views.students_all_list, name='students_all'),
    path('<int:pk>/', views.students_id, name='students_id'),
    path('course_id=<int:id>', views.students_list,
         name='students_list_course_id'),
    path('add', views.add_student, name='add_student'),
    path('edit/<int:pk>/', views.edit_student, name='edit_student'),
    path('delete/<int:pk>/', views.delete_student, name='delete_student'),
    ]

students/models.py
from django.db import models
from courses.models import Course


class Student(models.Model):
    name = models.CharField(max_length=64)
    surname = models.CharField(max_length=64)
    date_of_birth = models.DateField(help_text='Write yours date ofbirth',
                                     null=True, blank=True)
    email = models.EmailField(unique=True, max_length=64,
                              help_text='Write yours email')
    phone = models.CharField(unique=True, help_text='Write yours phone',
                             max_length=12)
    address = models.CharField(help_text='Write yours adress',
                               max_length=244, null=True, )
    skype = models.CharField(help_text='Write yours skype',
                             max_length=64, null=True, blank=True)
    courses = models.ManyToManyField(Course)

    def __str__(self):
        return (self.name)

# Create your models here.

students/forms.py
from django.forms import ModelForm
from .models import Student


class StudentModelForm(ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'surname', 'email', 'date_of_birth', 'phone',
                  'courses',]

students/views.py
from django.shortcuts import render, redirect
from students.models import Student
from django.urls import reverse
from django.contrib import messages
from students.utils import detail_view
from courses import models
from .forms import StudentModelForm


def students_list(request, id):
    course = models.Course.objects.get(id=id)
    student_information = Student.objects.filter(courses=course)
    return render(request, 'students/students.html',
                  {'student_information': student_information})


def students_all_list(request):
    student_all = Student.objects.all()
    return render(request, 'students/students_all.html',
                  {'student_all': student_all})


def students_id(request, pk):
    return detail_view(request, pk, Student)


def add_student(request):
    if request.method == 'POST':
        form = StudentModelForm(request.POST)
        if form.is_valid():
            instance = form.save()
            messages.success(request, "Saved!")
            return redirect(reverse('students:edit_student',
                                    args=[instance.id]))
    else:
        form = StudentModelForm(initial={'courses': 'assa'})
    return render(request, 'students/add_student_form.html', {'form': form})


def edit_student(request, pk):
    student_edit = Student.objects.get(id=pk)
    if request.method == 'POST':
        form = StudentModelForm(request.POST, instance=student_edit)
        if form.is_valid():
            student_edit = form.save()
            messages.success(request, 'Your profile was edit.')
            return redirect(reverse('students:students_all'))
    else:
        form = StudentModelForm(instance=student_edit)
    return render(request, 'students/add_student_form.html', {'form': form})


def delete_student(request, pk):
    delete_student = Student.objects.get(id=pk)
    if request.method == 'POST':
        delete_student.save()
        messages.success(request, 'Your profile was delete.')
        return redirect(reverse('students:students_all'))
    return render(request, 'students/delete_student.html',
                  {'delete_student': delete_student})
# Create your views here.

'''
    if request.method == 'POST':
        form = StudentModelForm(request.POST)
        if form.is_valid():
            instance = form.save()
            messages.success(request, "Saved!")
            return redirect(reverse('courses:edit_courses', args=[instance.id]))
    else:
        form = StudentModelForm(initial={'name': 'Akio the Beast'})
        
        
        
def students_id(request, student_id):
    student_personal = Student.objects.filter(id=student_id)
    return render(request, 'students/detail.html',
                  {'student_personal': student_personal})
                  
                  
    number = int(id)
    if number == 1:
        course = models.Course.objects.get(id=1)
        student_information = Student.objects.filter(courses=course)
    elif number == 2:
        course = models.Course.objects.get(id=2)
        student_information = Student.objects.filter(courses=course)
    elif number == 3:
        course = models.Course.objects.get(id=3)
        student_information = Student.objects.filter(courses=course)
'''

students/templates/students/add_student_form.html
{% extends 'base.html' %}

{% block title %}Main Page{% endblock title %}


{% block nav_class_active %}active{% endblock nav_class_active %}


{% block main_content %}


<div class= "mt-4 mb-4 mr-5 ml-5">
  <div>
    <h2>Добавить Student</h2>
    {% if messages %}
    <ul class="messages">
      {% for message in messages  %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
      </li>{% endfor %}
    </ul>
    {% endif %}
  </div>
  <div>
    <form method="post" >
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" />
    </form>
  </div>
</div>


{% endblock main_content %}

students/templates/students/base_students.html
{% extends 'base.html' %}

{% block title %}Student list{% endblock title %}


{% block nav_class_students %}active{% endblock nav_class_students %}

{% block main_content %}

  <div class= "mt-4 mb-4 mr-5 ml-5">
      <h1>{% block table_name %}Список студентов{% endblock table_name%}</h1>
  </div>
  <div class= "mt-4 mb-4 mr-5 ml-5">
    <a href="{% url 'students:add_student' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Добавить Student</a>
  </div>
  <div class= "mt-4 mb-4 mr-5 ml-5">
{% block table_information %}
    <table class="table table-striped ">
        <thead>
          <tr>
            <th scope="col">Имя</th>
            <th scope="col">Фамилия</th>
            <th scope="col">адресс</th>
            <th scope="col">Skype</th>
            <th scope="col">Курсы</th>
          </tr>
        </thead>
        <tbody>
          <tr>
{% for studens in student_all %}
              <td class="align-middle"><a href="{% url 'students:students_id' studens.id %}">{{studens}}</a></td>
            <td class="align-middle">{{ studens.surname }}</td>
            <td class="align-middle">{{ studens.address }}</td>
            <td class="align-middle">{{ studens.skype }}</td>
            <td>
    {% for course in studens.courses.all%}
              <p class="mt-1 mb-1"><a href="{% url 'courses:courses' course.id %}">{{ course.name }}</a></p>
    {% endfor %}
            </td>
            <td class="align-middle">
              <a href="{% url 'students:edit_student' studens.id %}" class="btn btn-primary btn-sm active small" role="button" aria-pressed="true">Edit Student</a
            </td>
            <td class="align-middle">
              <a href="{% url 'students:delete_student' studens.id %}" class="btn btn-primary btn-sm active small" role="button" aria-pressed="true">Delete Student</a>
            </td>

          </tr>
{% endfor %}
        <tr>
        </tbody>
      </table>
{% endblock table_information %}
  </div>
{% endblock main_content %}

students/templates/students/delete_student.html
{% extends 'base.html' %}

{% block title %}Main Page{% endblock title %}


{% block nav_class_active %}active{% endblock nav_class_active %}


{% block main_content %}


<div class= "mt-4 mb-4 mr-5 ml-5">
  <div>
    <h2>Удалить Student</h2>
  </div>
  <div>
    {{ delete_student.name }}
    <form method="post" >
    {% csrf_token %}
    <input type="submit" />
    </form>
  </div>
</div>


{% endblock main_content %}

students/templates/students/detail.html
{% extends 'base.html' %}

{% block main_content%}

<h1>{{ student.name }}</h1>

<div class="mt-4 mb-4 mr-5 ml-5">

</div>
<div class="mt-4 mb-4 mr-5 ml-5 w-50">
  <table class="table table-striped">
    <tbody>
      <tr>
        <td>Дата Рождения</td>
        <td>{{ student.date_of_birth }}</td>
      </tr>
      <tr>
        <td>Адресс</td>
        <td>{{ student.address }}</td>
    </tr>
     <tr>
        <td>Почта</td>
        <td>{{ student.email }}</td>
    <tr>
        <td>Логин Скайп</td>
        <td>{{ student.skype }}</td>
    </tr>
     <tr>
        <td>Телефон</td>
        <td>{{ student.phone }}</td>
     </tr>
        <td>Курсы</td>
        <td>
{% for course in student.courses.all %}
          <p class="mt-1 mb-1"><a href="{% url 'courses:courses' course.id %}">{{ course.name }}</a></p>
{% endfor %}

        </td>
    <tr>
    </tbody>
  </table>
</div>

{% endblock main_content %}

students/templates/students/edit_student.html
{% extends 'base.html' %}

{% block title %}Main Page{% endblock title %}


{% block nav_class_active %}active{% endblock nav_class_active %}


{% block main_content %}


<div class= "mt-4 mb-4 mr-5 ml-5">
  <div>
    <h2>Редактировать Курс</h2>
    {% if messages %}
    <ul class="messages">
      {% for message  in  messages  %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
      </li>{% endfor %}
    </ul>
    {% endif %}
  </div>
  <div>
    <form method="post" >

    {{ form.as_p }}
    {% csrf_token %}

    <input type="submit" />
    </form>
  </div>
</div>


{% endblock main_content %}

students/templates/students/students.html
{% extends 'students/base_students.html' %}

{% block title %}Student course list{% endblock title %}


{% block table_name %}Весь Список студентов{% endblock table_name %}


{% block table_information %}


  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Имя</th>
        <th scope="col">Фамилия</th>
        <th scope="col">адресс</th>
        <th scope="col">Skype</th>
        <th scope="col">курсы</th>
      </tr>
    </thead>
    <tbody>
      <tr>
{% for studens in student_information %}
        <td class="align-middle"><a href="{% url 'students:students_id' studens.id %}">{{ studens }}</a></td>
        <td class="align-middle">{{ studens.surname }}</td>
        <td class="align-middle">{{ studens.address }}</td>
        <td class="align-middle">{{ studens.skype }}</td>
        <td>
          {% for course in studens.courses.all %}
          <p class="mt-1 mb-1"><a href="{% url 'courses:courses' course.id %}">{{ course.name }}</a></p>
          {% endfor %}
        <td>
      </tr>
      {% endfor %}
      <tr>
    </tbody>
  </table>
{% endblock table_information %}

students/templates/students/students_all.html
{% extends 'students/base_students.html' %}

students/templates/students/students_person.html
{% extends 'base.html' %}

{% block main_content%}

<div class="mt-4 mb-4 mr-5 ml-5">
{% for student in student_personal %}
<h1>{{ student.name }}</h1>
</div>
<div class="mt-4 mb-4 mr-5 ml-5 w-50">
  <table class="table table-striped">
    <tbody>
      <tr>
        <td>Дата Рождения</td>
        <td>{{ student.date_of_birth }}</td>
      </tr>
      <tr>
        <td>Адресс</td>
        <td>{{ student.address }}</td>
    </tr>
     <tr>
        <td>Почта</td>
        <td>{{ student.email }}</td>
    <tr>
        <td>Логин Скайп</td>
        <td>{{ student.skype }}</td>
    </tr>
     <tr>
        <td>Телефон</td>
        <td>{{ student.phone }}</td>
     </tr>
        <td>Курсы</td>
        <td>
{% for course in student.courses.all %}
          <p class="mt-1 mb-1"><a href="{% url 'courses:courses' course.id %}">{{ course.name }}</a></p>
{% endfor %}

        </td>
    <tr>
{% endfor %}
    </tbody>
  </table>
</div>

{%  endblock main_content%}