coaches/urls.py
from django.urls import path
from coaches.views import personal_teacher


app_name = 'coaches'


urlpatterns = [
    path('<int:id>', personal_teacher, name='coaches_personal'),
    ]

hello/urls.py
from django.contrib import admin
from django.urls import path
from django.shortcuts import render
from django.urls import include
from students.views import students_list, students_all_list, students_id

# from instructors.views import hello,hello_http, views_about_course,views_student, views_student_detail, instructors_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('students/', include('students.urls', namespace='students')),
    path('coaches/', include('coaches.urls', namespace='coaches')),
]

templates/include/include_index.html
<div class="jumbotron jumbotron-fluid mt-4 mb-4 mr-5 ml-5 rounded" >
         <div class="container ">
           <h1 class="display-4">{{ block_title }}</h1>
           <p class="lead">{{ description }}</p>
         </div>
</div>

templates/include/instructor_include.html
<div class="card mt-4 mb-4 mr-5 ml-5">
  <div class="card-header">
    {{ position }}
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
        {% url 'coaches:coaches_personal' course.coach.id as the_url_coach %}
        {% url 'coaches:coaches_personal' course.assistant.id as the_url_assistant %}
        {% if instructor_name == course.coach.first_name %}
        <p><a href="{{ the_url_coach }}">{{ instructor_name }}</a></p>
        {% else %}
        <p><a href="{{ the_url_assistant }}">{{ instructor_name }}</a></p>
        {% endif%}
      <footer class="blockquote-footer">{{ instructor_description }}</footer>
    </blockquote>
  </div>
</div>