courses/urls.py
from django.urls import path
from courses import views


app_name = 'courses'

urlpatterns = [
    path('', views.index, name='main'),
    path('contacts', views.contacts, name='contacts'),
    path('courses/<int:pk>/', views.courses, name='courses'),
    path('courses/add', views.add_view_course, name='add_courses'),
    path('courses/edit/<int:pk>/', views.edit_view_course,
         name='edit_courses'),
    path('courses/delete/<int:pk>/', views.delete_course,
         name='delete_courses'),
    path('courses/add_lesson', views.add_view_lesson, name='add_lesson'),
    path('courses/edit_lesson/<int:pk>', views.edit_lesson,
         name='edit_lesson'),
    path('courses/delete_lesson/<int:pk>', views.delete_lesson,
         name='delete_lesson'),
    ]

hello/urls.py
from django.contrib import admin
from django.urls import path
from django.shortcuts import render
from django.urls import include
from students.views import students_list, students_all_list, students_id

# from instructors.views import hello,hello_http, views_about_course,views_student, views_student_detail, instructors_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('students/', include('students.urls', namespace='students')),
    path('coaches/', include('coaches.urls', namespace='coaches')),
]

students/urls.py
from django.urls import path
from students import views

app_name = 'students'

urlpatterns = [
    path('', views.students_all_list, name='students_all'),
    path('<int:pk>/', views.students_id, name='students_id'),
    path('course_id=<int:id>', views.students_list,
         name='students_list_course_id'),
    path('add', views.add_student, name='add_student'),
    path('edit/<int:pk>/', views.edit_student, name='edit_student'),
    path('delete/<int:pk>/', views.delete_student, name='delete_student'),
    ]

courses/models.py
from django.db import models


class Course(models.Model):
    name = models.CharField(verbose_name='Name of the course', max_length=64)
    short_description = models.CharField(max_length=122,
                                         help_text='Short description ofthe course',
                                         null=True,
                                         blank=True)
    description = models.TextField(help_text='Full description of the course',
                                   max_length=255,
                                   null=True,
                                   blank=True)
    coach = models.ForeignKey('coaches.Coach', on_delete=models.CASCADE,
                              related_name='coach_courses',
                              null=True,
                              blank=True)
    assistant = models.ForeignKey('coaches.Coach', on_delete=models.CASCADE,
                                  related_name='assistants_courses',
                                  null=True,
                                  blank=True)

    def __str__(self):
        return self.name


class Lesson(models.Model):
    subject = models.CharField(verbose_name='Subject',
                               max_length=64,
                               help_text='Subject')
    description = models.TextField(max_length=255,
                                   help_text='description of the Subject',
                                   null=True, blank=True)
    course = models.ForeignKey('Course', on_delete=models.CASCADE, )
    order = models.PositiveIntegerField()

    def __str__(self):
        return self.subject

# Create your models here.

courses/forms.py
from django.forms import ModelForm
from .models import Course, Lesson
from django.forms import Textarea


class LessonModelForm(ModelForm):
    class Meta:
        model = Lesson
        fields = ['subject', 'description', 'course', 'order' ]


class CourseModelForm(ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'coach', 'assistant', 'description']
        #widgets = {'coach': Textarea(attrs={'cols': 20, 'rows': 1})}
        labels = {'description': 'Description'}

courses/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.urls import reverse
from .models import Course, Lesson
from .forms import CourseModelForm, LessonModelForm


def index(request):
    course = Course.objects.all()
    return render(request, 'courses/index.html', {'course': course})


def contacts(request):
    return render(request, 'courses/contacts.html', )


def courses(request, pk):
    course = get_object_or_404(Course, id=pk)
    lessons = Lesson.objects.filter(course=course)  # filtration in
    return render(request, 'courses/detail.html', {'course': course,
                                                   'lessons': lessons})


def add_view_course(request):
    if request.method == 'POST':
        form = CourseModelForm(request.POST)
        if form.is_valid():
            instance = form.save()
            messages.success(request, "Saved!")
            return redirect(
                reverse('courses:edit_courses', args=[instance.id]))
    else:
        form = CourseModelForm(initial={'coach': 'Akio the Beast'})
    return render(request, 'courses/add_form.html', {'form': form})


def edit_view_course(request, pk):  # now you could edit this form
    course_edit = Course.objects.get(id=pk)
    if request.method == 'POST':
        form = CourseModelForm(request.POST, instance=course_edit)
        if form.is_valid():
            course_edit = form.save()
            messages.success(request, 'Your profile was edit.')
            return redirect(reverse('courses:main'))
    else:
        form = CourseModelForm(instance=course_edit)
    return render(request, 'courses/edit_course.html', {'form': form})


def delete_course(request, pk):
    course_delete = Course.objects.get(id=pk)
    if request.method == 'POST':
        course_delete.delete()
        messages.success(request, 'Your {} deleted.'.format(
            course_delete.name))
        return redirect('/courses/add_lesson')
    return render(request, 'courses/delete_course.html',
                  {'course_delete': course_delete})


def add_view_lesson(request):
    #  model_form=CourseModelForm(initial={'coach':'Akio the Beast'}) dont need
    if request.method == 'POST':
        form = LessonModelForm(request.POST)
        if form.is_valid():
            instance = form.save()
            messages.success(request, 'Your lesson was added.')
            return redirect(reverse('courses:edit_lesson', args=[instance.id]))
    else:
        form = LessonModelForm()
    return render(request, 'courses/add_lesson.html', {'form': form})


def edit_lesson(request, pk):
    lesson = Lesson.objects.get(id=pk)
    course = Course.objects.get(lesson=lesson)
    if request.method == 'POST':
        form = LessonModelForm(request.POST, instance=lesson)
        if form.is_valid():
            lesson = form.save()
            messages.success(request, 'Your lesson was eddit.')
            return redirect(reverse('courses:courses', args=[course.id]))
    else:
        form = LessonModelForm(instance=lesson)
        return render(request, 'courses/edit_lesson.html', {'form': form})


def delete_lesson(request, pk):
    lesson_delete = Lesson.objects.get(id=pk)
    course = Course.objects.get(lesson=lesson_delete)
    if request.method == 'POST':
        lesson_delete.delete()
        messages.success(request, 'Your {} deleted.'.format(
            lesson_delete.subject))
        return redirect(reverse('courses:courses', args=[course.id]))
    return render(request, 'courses/delete_lesson.html',
                  {'lesson_delete': lesson_delete})


# Create your views here.

'''


def courses(request, indification_number):
    int_number_page = int(indification_number)
    if int_number_page == 1:
        course = Course.objects.get(id=1)
        lessons = Lesson.objects.filter(course=course)  # filtration in foreing
    #  key
    elif int_number_page == 2:
        course = Course.objects.get(id=2)
        lessons = Lesson.objects.filter(course=course)  # filtration in
# foreingkey
    elif int_number_page == 3:
        course = Course.objects.get(id=3)
        lessons = Lesson.objects.filter(course=course)  # filtration in
        # foreing key
    return render(request, 'courses/detail.html', {'course': course,
                                                 'lessons': lessons})                                      
def index(request):
latest_question_list = Question.objects.order_by('-pub_date')[:5]
content = {
'latest_question_list': latest_question_list,
}
return render(request, 'polls/index.html', content)

class IndexView(generic.ListView):
template_name = 'polls/index.html'
context_object_name = 'latest_question_list'
def get_queryset(self):
""Return the last five published questions."""
return Question.objects.order_by('-pub_date')[:5]
'''

courses/templates/courses/add_form.html
{% extends 'base.html' %}

{% block title %}Main Page{% endblock title %}


{% block nav_class_active %}active{% endblock nav_class_active %}


{% block main_content %}


<div class= "mt-4 mb-4 mr-5 ml-5">
  <div>
    <h2>Добавить Курс</h2>
    {% if messages %}
    <ul class="messages">
      {% for message  in  messages  %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
      </li>{% endfor %}
    </ul>
    {% endif %}
  </div>
  <div>
    <form method="post" >

    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" />
    </form>
  </div>
</div>


{% endblock main_content %}

courses/templates/courses/add_lesson.html
{% extends 'base.html' %}

{% block title %}Main Page{% endblock title %}


{% block nav_class_active %}active{% endblock nav_class_active %}


{% block main_content %}

<div class= "mt-4 mb-4 mr-5 ml-5">
  <div>
    <h2>Добавить Урок</h2>
    {% if messages %}
    <ul class="messages">
      {% for message  in  messages  %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
      </li>{% endfor %}
    </ul>
    {% endif %}
  </div>
  <div>
    <form method="post" >

    {{ form.as_p }}
    {% csrf_token %}

    <input type="submit" />
    </form>
  </div>
</div>

{% endblock main_content %}

courses/templates/courses/contacts.html
{% extends 'base.html' %}


{% block title %}Contacts Page{% endblock title %}


{% block nav_class_contacts %}active{% endblock nav_class_contacts %}


{% block main_content %}

<div class="card-group mt-4 mb-4 mr-5 ml-5">
  <div class="card ">
    <img class="rounded float-left img-thumbnai img-fluid pl-5 pr-5 pt-3"   src="http://www.avatar-mix.ru/avatars_200x200/1397.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">{% filter force_escape|upper %}This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.{% endfilter %}</p>
    </div>
  </div>
  <div class="card">
    <img class="rounded float-left img-thumbnai img-fluid pl-5 pr-5 pt-3" src="http://www.avatar-mix.ru/avatars_200x200/1397.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content. {% now " F Y H:i" %}</p>
    </div>
  </div>
  <div class="card">
    <img class="rounded float-left img-thumbnai img-fluid pl-5 pr-5 pt-3" src="http://www.avatar-mix.ru/avatars_200x200/1397.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
  </div>
</div>

{% endblock main_content %}

courses/templates/courses/courses.html
{% extends 'base.html' %}


{% block title %}Course page{% endblock title %}


{% block students_of_the_course %}{% url 'students:students_list_course_id' course.id %}{% endblock students_of_the_course %}


{% block main_content %}


{% include 'include/include_index.html' with block_title=course description=course.description|truncatechars:39 %}

<h1 class="mt-4 mb-4 mr-5 ml-5">Main Teacher</h1>


{% include 'include/instructor_include.html' with  position='Учитель' instructor_name=course.coach.first_name instructor_description=course.coach.description %}
{% include 'include/instructor_include.html' with  position='Ассистент' instructor_name=course.assistant.first_name instructor_description=course.assistant.description %}

<h1 class="mt-4 mb-4 mr-5 ml-5">План курса</h1>
<div class="mt-4 mb-4 mr-5 ml-5">
  <a href="{% url 'courses:add_lesson' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Добавить Урок</a>
</div>
<div class="mt-4 mb-4 mr-5 ml-5">
  <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">№</th>
          <th scope="col">Тема</th>
          <th scope="col">Описание</th>
        </tr>
      </thead>
      <tbody>
        <tr>
{% for lesson in lessons %}
          <td>{{ lesson.id }}</td>
          <td>{{ lesson }}</td>
          <td>{{ lesson.description }}</td>
        </tr>
{% endfor %}
      <tr>
          </tr>
      </tbody>
    </table>
</div>

{% endblock main_content %}

courses/templates/courses/delete_course.html
{% extends 'base.html' %}

{% block title %}Main Page{% endblock title %}


{% block nav_class_active %}active{% endblock nav_class_active %}


{% block main_content %}


<div class= "mt-4 mb-4 mr-5 ml-5">
  <div>
    <h2>Удалить Курс</h2>
  </div>
  <div>
    {{ course_delete.name }}
    <form method="post" >
    {% csrf_token %}
    <input type="submit" />
    </form>
  </div>
</div>


{% endblock main_content %}

courses/templates/courses/delete_lesson.html
{% extends 'base.html' %}

{% block title %}Main Page{% endblock title %}


{% block nav_class_active %}active{% endblock nav_class_active %}


{% block main_content %}


<div class= "mt-4 mb-4 mr-5 ml-5">
  <div>
    <h2>Удалить Курс</h2>
  </div>
  <div>
    {{ lesson_delete.subject }}
    <form method="post" >
    <input type="submit" />
    </form>
  </div>
</div>

{% endblock main_content %}

courses/templates/courses/detail.html
{% extends 'base.html' %}


{% block title %}Course page{% endblock title %}


{% block students_of_the_course %}{% url 'students:students_list_course_id' course.id %}{% endblock students_of_the_course %}


{% block main_content %}


{% include 'include/include_index.html' with block_title=course description=course.description|truncatechars:39 %}

<h1 class="mt-4 mb-4 mr-5 ml-5">Main Teacher</h1>


{% include 'include/instructor_include.html' with  position='Учитель' instructor_name=course.coach.first_name instructor_description=course.coach.description %}
{% include 'include/instructor_include.html' with  position='Ассистент' instructor_name=course.assistant.first_name instructor_description=course.assistant.description %}

<h1 class="mt-4 mb-4 mr-5 ml-5">План курса</h1>
<div class="mt-4 mb-4 mr-5 ml-5">
  <a href="{% url 'courses:add_lesson' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Добавить Урок</a>
</div>
<div class="mt-4 mb-4 mr-5 ml-5">
  <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">№</th>
          <th scope="col">Тема</th>
          <th scope="col">Описание</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
{% for lesson in lessons %}
          <td>{{ forloop.counter }}</td>
          <td>{{ lesson }}</td>
          <td>{{ lesson.description }}</td>
            <td>
              <a href="{% url 'courses:edit_lesson' lesson.id %}" class="btn btn-primary btn-sm active small" role="button" aria-pressed="true">Редактировать Урок</a>
          </td>
          <td>
              <a href="{% url 'courses:delete_lesson' lesson.id %}" class="btn btn-primary btn-sm active small" role="button" aria-pressed="true">Удалить Урок</a>
          </td>
        </tr>
{% endfor %}
      </tbody>
    </table>
</div>

{% endblock main_content %}

courses/templates/courses/edit_course.html
{% extends 'base.html' %}

{% block title %}Main Page{% endblock title %}


{% block nav_class_active %}active{% endblock nav_class_active %}


{% block main_content %}


<div class= "mt-4 mb-4 mr-5 ml-5">
  <div>
    <h2>Редактировать Курс</h2>
    {% if messages %}
    <ul class="messages">
      {% for message  in  messages  %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
      </li>{% endfor %}
    </ul>
    {% endif %}
  </div>
  <div>
    <form method="post" >

    {{ form.as_p }}

    <input type="submit" />
    </form>
  </div>
</div>


{% endblock main_content %}

courses/templates/courses/edit_lesson.html
{% extends 'base.html' %}

{% block title %}Main Page{% endblock title %}


{% block nav_class_active %}active{% endblock nav_class_active %}


{% block main_content %}


<div class= "mt-4 mb-4 mr-5 ml-5">
  <div>
    <h2>Редактировать Курс</h2>
    {% if messages %}
    <ul class="messages">
      {% for message  in  messages  %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
      </li>{% endfor %}
    </ul>
    {% endif %}
  </div>
  <div>
    <form method="post" >

    {{ form.as_p }}
    {% csrf_token %}

    <input type="submit" />
    </form>
  </div>
</div>

{% endblock main_content %}

courses/templates/courses/index.html
{% extends 'base.html' %}

{% block title %}Main Page{% endblock title %}


{% block nav_class_active %}active{% endblock nav_class_active %}


{% block main_content %}


{% include  "include/include_index.html" with block_title="Кодинг от Иоана" description="Если Вы новичок в программировании, обратитесь за консультацией в службу поддержки или воспользуйтесь Картой специальностей, чтобы спланировать последовательное изучение программирования и сопутствующих технологий от простого к сложному. Учебный курс включает в себя: обучение в мини-группе в современной мультимедийной аудитории, предоставляется ноутбук, блокнот, ручка; материалы курса в электронном виде: краткий конспект каждого занятия, практические примеры, презентации;онлайн тестирование с целью проверки усвоения материала после каждого занятия и итоговое по всему курсу; сертификат о прохождении курса (в случае успешной сдачи финального теста)" %}


  <div class= "mt-4 mb-4 mr-5 ml-5">
    <h1>Information about courses</h1>
    <div>
      <a href="{% url 'courses:add_courses' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Добавить Курс</a>
    </div>
  </div>
  <div class= "mt-4 mb-4 mr-5 ml-5">
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">№</th>
            <th scope="col">Курс</th>
            <th scope="col">Описание</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
{% for subjects in course %}
            <td>{{ forloop.counter }}</td>
            <td><a href="/courses/{{subjects.id}}">{{ subjects|upper }}</a></td>
            <td>{{ subjects.short_description|title }}</td>
            <td>
              <div>
                <a href="{% url 'courses:edit_courses' subjects.id %}" class="btn btn-primary btn-sm active small" role="button" aria-pressed="true">Редактировать</a>
              </div>
            </td>
            <td>
              <div>
                <a href="{% url 'courses:delete_courses' subjects.id %}" class="btn btn-primary btn-sm active small" role="button" aria-pressed="true">Удалить Курс</a>
              </div>
            </td>
          </tr>
          <tr>
{% endfor %}
        </tbody>
      </table>
</div>

{% endblock main_content %}