courses/urls.py
from django.urls import path
from courses import views


app_name = 'courses'

urlpatterns = [
    path('', views.index, name='main'),
    path('contacts', views.contacts, name='contacts'),
    path('courses/<int:pk>/', views.courses, name='courses'),
    path('courses/add', views.add_view_course, name='add_courses'),
    path('courses/edit/<int:pk>/', views.edit_view_course,
         name='edit_courses'),
    path('courses/delete/<int:pk>/', views.delete_course,
         name='delete_courses'),
    path('courses/add_lesson', views.add_view_lesson, name='add_lesson'),
    path('courses/edit_lesson/<int:pk>', views.edit_lesson,
         name='edit_lesson'),
    path('courses/delete_lesson/<int:pk>', views.delete_lesson,
         name='delete_lesson'),
    ]

hello/urls.py
from django.contrib import admin
from django.urls import path
from django.shortcuts import render
from django.urls import include
from students.views import students_list, students_all_list, students_id

# from instructors.views import hello,hello_http, views_about_course,views_student, views_student_detail, instructors_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('students/', include('students.urls', namespace='students')),
    path('coaches/', include('coaches.urls', namespace='coaches')),
]

students/urls.py
from django.urls import path
from students import views

app_name = 'students'

urlpatterns = [
    path('', views.students_all_list, name='students_all'),
    path('<int:pk>/', views.students_id, name='students_id'),
    path('course_id=<int:id>', views.students_list,
         name='students_list_course_id'),
    path('add', views.add_student, name='add_student'),
    path('edit/<int:pk>/', views.edit_student, name='edit_student'),
    path('delete/<int:pk>/', views.delete_student, name='delete_student'),
    ]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Main page{% endblock title %}</title>
    <!-- Bootstrap -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
    <body >
        <div>
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">
               <img src="{% static 'assets/brand/bootstrap-solid.svg' %}" width="30" height="30" alt="">
            </a>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="{% block nav_class_active %}{% endblock nav_class_active %}" class="nav-item nav-item bg-dark">
                    <a class="nav-link" href="{% url 'courses:main' %}">Main<span class="sr-only">(current)</span></a>
                  </li>
                  <li class="{% block nav_class_contacts %}{% endblock nav_class_contacts %}" class="nav-item bg-dark">
                    <a class="nav-link" href="{% url 'courses:contacts' %}">Contacts<span class="sr-only">(current)</span></a>
                  </li>
                  <li class="{% block nav_class_students %}{% endblock nav_class_students %}" class="nav-item bg-dark">
                      <a class="nav-link " href="{% block students_of_the_course %}{% url 'students:students_all' %}{% endblock students_of_the_course %}">Students<span class="sr-only">(current)</span></a>
                  </li>
                </ul>
              </div>
          </nav>
        </div>
{% block main_content %}

{% endblock main_content %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../static/js/bootstrap.min.js"></script>
  </body>
</html>
<!-- Bootstrap core JavaScript

templates/content.html
{% extends 'base.html' %}


{% block title %}Contacts Page{% endblock title %}


{% block main_content %}
</div>
  <div class="card-group  mt-4 mb-4 mr-5 ml-5">
  <div class="card ">
    <img class="rounded float-left img-thumbnai img-fluid pl-5 pr-5"   src="http://www.avatar-mix.ru/avatars_200x200/1397.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
  </div>
  <div class="card">
    <img class="rounded float-left img-thumbnai img-fluid pl-5 pr-5" src="http://www.avatar-mix.ru/avatars_200x200/1397.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
    </div>
  </div>
  <div class="card">
    <img class="rounded float-left img-thumbnai img-fluid pl-5 pr-5" src="http://www.avatar-mix.ru/avatars_200x200/1397.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
  </div>
</div>
{% endblock main_content %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>
    <!-- Bootstrap -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> 
          <a class="navbar-brand" href="/main/">Main</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item bg-dark">
                <a class="nav-link" href="/123/">Course<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item bg-dark">
                  <a class="nav-link " href="/student/">Students<span class="sr-only">(current)</span></a>
              </li>
          </div>
        </nav>
  </div>     
  <div>
    <h1>Information about course</h1>
  </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../static/js/bootstrap.min.js"></script>
  </body>
</html>
<!-- Bootstrap core JavaScript

templates/instructors.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>
    <!-- Bootstrap -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> 
          <a class="navbar-brand" href="/main/">Main</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item bg-dark">
                <a class="nav-link" href="/123/">Course<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item bg-dark">
                  <a class="nav-link " href="/student/">Students<span class="sr-only">(current)</span></a>
              </li>
          </div>
        </nav>
  </div class = 'container'>     
    <div class = 'jumbotron'>
    <h1>instructors</h1>
    {% for instructors in instructors_list %}
    <p>{{instructors.name}} {{instructors.surname}}</p>
    {% endfor %}
  </div>  
  </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../static/js/bootstrap.min.js"></script>
  </body>
</html>
<!-- Bootstrap core JavaScript

templates/student_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <link href="../static/css/test.css" rel="stylesheet">
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> 
            <a class="navbar-brand" href="/main/">Main</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item bg-dark">
                  <a class="nav-link" href="/123/">Course<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item bg-dark">
                    <a class="nav-link " href="/student/">Students<span class="sr-only">(current)</span></a>
                </li>
            </div>
          </nav>
  </div>  

  
  <div>
    <h2></h2>
    <p>Alyona</p>
    <img src="http://www.avatar-mix.ru/avatars_200x200/1397.jpg" alt="..." class="img-thumbnail, pull-left">    
    <div id="list-example" class="list-group rounded float-right">
        <a class="list-group-item list-group-item-action" href="#list-item-1">About Python</a>
        <a class="list-group-item list-group-item-action" href="#list-item-2">Organization</a>
        <a class="list-group-item list-group-item-action" href="#list-item-3">Program</a>
        <a class="list-group-item list-group-item-action" href="#list-item-4">Price</a>
        <a class="list-group-item list-group-item-action" href="#list-item-4">Couchs</a>        
    </div>
    <div>  
        <button type="button" class="btn btn-secondary btn-lg pull-left mt-2 mb-2">About Urself</button>
    </div>
  </div>
  <div>
    <p>Students Cards</p>
      <table class="table table-bordered">
     <div>
          <tbody class = "w-50 p-3">
            <tr></a>
              <th calss = "position-static" scope="row ">Surname</th>
              <td class = "w-50 p-3">Mark</td>            
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>Jacob</td>                     
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>Larry</td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>Larry</td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>Jacob</td>                     
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>Larry</td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>Larry</td>
            </tr>                  
          </tbody>
        </table>
        <div class = "pull-left w-75 p-3"></div>    
    </div>             
  </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../static/js/bootstrap.min.js"></script>
  </body>
</html>
<!-- Bootstrap core JavaScript

templates/student_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> 
            <a class="navbar-brand" href="/main/">Main</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item bg-dark">
                  <a class="nav-link" href="/123/">Course<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item bg-dark">
                    <a class="nav-link " href="/student/">Students<span class="sr-only">(current)</span></a>
                </li>
            </div>
          </nav>
  </div>  

  
  <div>
    <h2>Course PyBursa</h2>
    
  </div>
        
  <div>
    <p>Students of the Course</p>
      <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">First</th>
              <th scope="col">Last</th>
              <th scope="col">Handle</th>
              <th scope="col">Skype</th>              
            </tr>
          </thead>
          <tbody>
            <tr></a>
              <th scope="row"><a href="/student_detail/">1</a></th>
              <td>Mark</td>
              <td>Otto</td>
              <td>@mdo</td>
              <td>Monty Python</td>              
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>Jacob</td>
              <td>Thornton</td>
              <td>@fat</td>
              <td>Monty Python</td>                            
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>Larry</td>
              <td>the Bird</td>
              <td>@twitter</td>
              <td>Monty Python</td>                                          
            </tr>
          </tbody>
        </table>
  </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../static/js/bootstrap.min.js"></script>
  </body>
</html>
<!-- Bootstrap core JavaScript